# Generated by Django 4.0.1 on 2022-06-10 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adoption", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adoption",
            old_name="valor",
            new_name="value",
        ),
    ]
